### ISSUE TITLE
Unable to login 

### ISSUE THREAD

**Issue by memanj** [dwighthubbard/python-dlipower#34]
I am seeing below message when I try to connect using dlipower.
dlipower.PowerSwitch(hostname="10.1.48.11", userid="admin", password="1234")
**Digital Loggers Web Powerswitch 10.1.48.11 (UNCONNECTED)**

Also on the server log below I see below error message for every attempt using dlipower module.
Jun 19 21:20:26 LPC970 user.notice auth[1494]: login denied for admin@10.1.48.158 (plaintext): password check failed
Jun 19 21:20:26 LPC970 user.notice www[1510]: login admin failed from 10.1.48.158

Any help on this would be much appreciated.

**Comment by aaronslow** [comment]
For logins to work, you need to change the access settings on the main webpage.
Access settings
--
Allow legacy plaintext login methods (enable)

**Comment by dwighthubbard** [comment]
This should be fixed
