### ISSUE TITLE
Python 3 will not connect

### ISSUE THREAD

**Issue by LBeaufore** [dwighthubbard/python-dlipower#9]
I developed a python 2.7 application that made use of this library (which was very helpful). However, the project recently switched to python 3.5. After the switch, we noticed that our switch no longer connected with the library. Instead:
```
>>> import dlipower
>>> switch = dlipower.PowerSwitch(hostname='ourhostname', userid='admin', password='*****')
>>> switch
Digital Loggers Web Powerswitch ourhostname (UNCONNECTED)
```

The library still behaves correctly if these same commands are used in 2.7.

**Comment by dwighthubbard** [comment]
The newest release passes tests against py27, py34, py35, and pypy.  Let me know if you are still seeing this issue.
